################################################################################
# Automatically-generated file. Do not edit!
################################################################################

INO_SRCS := 
ASM_SRCS := 
O_UPPER_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
PDE_SRCS := 
CC_SRCS := 
AR_SRCS := 
EEP_SRCS := 
C_SRCS := 
C_UPPER_DEPS := 
PDE_DEPS := 
C_DEPS := 
AR := 
EEP := 
FLASH_IMAGE := 
CC_DEPS := 
AR_OBJ := 
C++_DEPS := 
LINK_OBJ := 
CXX_DEPS := 
ASM_DEPS := 
INO_DEPS := 
SIZEDUMMY := 
S_UPPER_DEPS := 
ELF := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
Bridge/1.6.2/examples/Bridge \
Bridge/1.6.2/examples/ConsoleAsciiTable \
Bridge/1.6.2/examples/ConsolePixel \
Bridge/1.6.2/examples/ConsoleRead \
Bridge/1.6.2/examples/Datalogger \
Bridge/1.6.2/examples/FileWriteScript \
Bridge/1.6.2/examples/HttpClient \
Bridge/1.6.2/examples/HttpClientConsole \
Bridge/1.6.2/examples/MailboxReadMessage \
Bridge/1.6.2/examples/Process \
Bridge/1.6.2/examples/RemoteDueBlink \
Bridge/1.6.2/examples/ShellCommands \
Bridge/1.6.2/examples/SpacebrewYun/inputOutput \
Bridge/1.6.2/examples/SpacebrewYun/spacebrewBoolean \
Bridge/1.6.2/examples/SpacebrewYun/spacebrewRange \
Bridge/1.6.2/examples/SpacebrewYun/spacebrewString \
Bridge/1.6.2/examples/TemperatureWebPanel \
Bridge/1.6.2/examples/TimeCheck \
Bridge/1.6.2/examples/WiFiStatus \
Bridge/1.6.2/examples/YunFirstConfig \
Bridge/1.6.2/examples/YunSerialTerminal \
Bridge/1.6.2/src \
Bridge/examples/Bridge \
Bridge/examples/ConsoleAsciiTable \
Bridge/examples/ConsolePixel \
Bridge/examples/ConsoleRead \
Bridge/examples/Datalogger \
Bridge/examples/FileWriteScript \
Bridge/examples/HttpClient \
Bridge/examples/MailboxReadMessage \
Bridge/examples/Process \
Bridge/examples/ShellCommands \
Bridge/examples/SpacebrewYun/inputOutput \
Bridge/examples/SpacebrewYun/spacebrewBoolean \
Bridge/examples/SpacebrewYun/spacebrewRange \
Bridge/examples/SpacebrewYun/spacebrewString \
Bridge/examples/Temboo/GetYahooWeatherReport \
Bridge/examples/Temboo/ReadATweet \
Bridge/examples/Temboo/SendATweet \
Bridge/examples/Temboo/SendAnEmail \
Bridge/examples/Temboo/SendAnSMS \
Bridge/examples/Temboo/SendDataToGoogleSpreadsheet \
Bridge/examples/Temboo/ToxicFacilitiesSearch \
Bridge/examples/Temboo/UpdateFacebookStatus \
Bridge/examples/Temboo/UploadToDropbox \
Bridge/examples/TemperatureWebPanel \
Bridge/examples/TimeCheck \
Bridge/examples/WiFiStatus \
Bridge/examples/YunSerialTerminal \
Bridge/src \
core/core \
core/core/libb64 \
core/core/spiffs \
core/core/umm_malloc \
libraries/ESP8266WiFi/src \
libraries/Ethernet/src \
libraries/Ethernet/src/utility \
libraries/SPI \
libraries/ThingSpeak/src \
libraries/WiFi/src \
libraries/WiFi/src/utility \

